    # https://www.youtube.com/watch?v=encpjND99xU


name: FiveM Overlay

on: 
  push:
    branches: [deploy]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2 
    - name: Deploy
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn run build